services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lockbin
      POSTGRES_PASSWORD: Password123
    volumes:
      - ./data/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/timescaledb:/var/lib/postgresql/data

#environment:
# LOCKBIN_HOST: timescaledb